const EventType = {
  DATABASE_SETTING_SHOW: 'DATABASE_SETTING_SHOW',
  DATABASE_CONFIG_CHANGE: 'DATABASE_CONFIG_CHANGE',
  DATABASE_NAME_CHANGE: 'DATABASE_NAME_CHANGE',
  DATABASE_LIST_CHANGE: 'DATABASE_LIST_CHANGE',
  DATABASE_DATA_LOAD: 'DATABASE_DATA_LOAD',
  TABLE_LIST_CHANGE: 'TABLE_LIST_CHANGE',
  TABLE_DATA_CHANGE: 'TABLE_DATA_CHANGE',
  TABLE_COMMENT_CHANGE: 'TABLE_COMMENT_CHANGE',

  PROJECT_SETTING_SHOW: 'PROJECT_SETTING_SHOW',
  PROJECT_CONFIG_CHANGE: 'PROJECT_CONFIG_CHANGE'
}

export default EventType
